version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty1
      MYSQL_DATABASE: realworld_db
      MYSQL_USER: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/loib/mysql
    ports:
      - 3306:3306

volumes:
  db_data:
